---
- name: "Create /etc/module-load.d if not existent"
  file:
    path: /etc/module-load.d
    state: directory

- name: "Template file to /etc/module-load.d/crio.conf"
  template:
    src: "module.conf"
    dest: "/etc/module-load.d/crio.conf"
    owner:
    group:
    mode: u=rw,g=r,o=r
  become: true

- modprobe: 
    name: overlay
    state: present

- modprobe:
    name: br_netfilter
    state: present

- name: "Template file to /etc/sysctl.d/99-kubernetes-cri.conf"
  template:
    src: "99-kubernetes-cri.conf"
    dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
    owner:
    group:
    mode: u=rw,g=r,o=r

- name: "Reload Sysctl"
  shell: sysctl --system
  become: true

- name: "Ensure dependencies are installed."
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - gnupg2
    - curl
    - software-properties-common
    state: present

- name: "Add libcontainers Repo Key"
  become: yes
  apt_key:
    id: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4 
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/Release.key"
    keyring: /etc/apt/trusted.gpg.d/libcontainers.gpg

- name: "Add libcontainers (crio) Repo Key"
  become: yes
  apt_key:
    id: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4 
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/Release.key"
    keyring: /etc/apt/trusted.gpg.d/libcontainers.gpg

- name: "Add libcontainers Repo"
  become: yes
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/ /"
    state: present
    filename: "devel-kubic-libcontainers-stable"

- name: "Add libcontainers (crio) Repo"
  become: yes
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ VERSION }}/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/ /"
    state: present
    filename: "devel-kubic-libcontainers-stable-cri-o-{{ VERSION }}"
  
- name: "Add Deb-Backport repository for {{ OS_CODENAME }}"
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ OS_CODENAME }}-backports main"
    state: present
    update_cache: true
    
- name: "Install libseccomp-dev from {{ OS_CODENAME }}-backports"
  apt:
    name: libseccomp-dev
    state: latest
    default_release: "{{ OS_CODENAME }}-backports"
    update_cache: yes

- name: "Install crio"
  apt:
    name:
    - cri-o
    - cri-o-runc
    state: present

- name: "Template file to /etc/crio/crio.conf.d/02-cgroup-manager.conf"
  template:
    src: "cgroup.conf"
    dest: "/etc/crio/crio.conf.d/02-cgroup-manager.conf"
    owner:
    group:
    mode: u=rw,g=r,o=r
    
- name: "Create /etc/module-load.d if not existent"
  file:
    path: /etc/systemd/system/crio.service.d
    state: directory
  
- name: "Create Service Config for Proxy"
  template:
    src: "http-proxy.conf"
    dest: "/etc/systemd/system/crio.service.d/http-proxy.conf"
    owner: 
    group:
    mode: u=rw,g=r,o=r

- name: "Daemon-Reload and restart cri-o.serivce"
  systemd:
    daemon_reload: yes
    name: cri-o.service
    state: restarted

- name: "Restart cri-o.service"
  service:
    name: cri-o
    state: restarted
